#!/usr/bin/env bash
# install ansible
sudo apt install software-properties-common
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible

# run ansible playbook
ansible-playbook  local.yml  -K --ask-vault-pass