---
- name: Local Setup
  hosts: localhost
  connection: local
  gather_facts: false 
  vars:
    source_key: ./.ssh/ansible
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/ansible"
  pre_tasks:
    - name: Update Apt
      become: true
      #accept_hostkey: yes
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present

  tasks:
    - name: setup SSH
      ansible.builtin.include_tasks:
        file: tasks/ssh.yml
      tags: ssh
    - name: Execute Git Setup
      ansible.builtin.include_tasks:
        file: tasks/git-setup.yml
      tags: git
    - name: Execute Core Setup
      ansible.builtin.include_tasks:
        file: tasks/core-setup.yml
      tags: core
    - name: Execute ZSH Setup
      ansible.builtin.include_tasks:
        file: tasks/zsh-setup.yml
      tags: zsh
    - name: Execute NVIM Setup
      ansible.builtin.include_tasks:
        file: tasks/nvim-setup.yml
      tags: nvim
    - name: Execute Setup productivity tools
      ansible.builtin.include_tasks:
        file: tasks/productivity-tools.yml
      tags: tools
    - name: Execute Brave Setup
      ansible.builtin.include_tasks:
        file: tasks/brave.yml
      tags: brave
    - name: setup Dotfiles
      ansible.builtin.include_tasks:
        file: tasks/dotfiles.yml
      tags: dotfiles