---
- name: Local Setup
  hosts: localhost
  vars:
    source_key: ./.ssh/ansible
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/ansible"
  pre_tasks:
    - name: Update Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present

  tasks:
    - name: Execute Tasks 1
      ansible.builtin.include_tasks:
        file: tasks/git-setup.yml
    - name: Execute Tasks 2
      ansible.builtin.include_tasks:
        file: tasks/core-setup.yml
    - name: Execute Tasks 3
      ansible.builtin.include_tasks:
        file: tasks/zsh-setup.yml
    - name: Execute Tasks 4
      ansible.builtin.include_tasks:
        file: tasks/nvim-setup.yml
    - name: Execute Tasks 5
      ansible.builtin.include_tasks:
        file: tasks/productivity-tools.yml
    - name: Execute Tasks 6
      ansible.builtin.include_tasks:
        file: tasks/brave.yml
#     tasks/dotfiles.yml
#     tasks/ssh.yml
