---
- name: Install packages
  become: true
  ansible.builtin.apt:
    name: [tmux, wireshark, fzf, gimp, ripgrep, python3-pip, pipx ]
  tags:
    - install
    - productivity
  
- name: Install tldr
  become: true
  ansible.builtin.shell: pipx install tldr
  tags:
    - install
    - productivity
    - tldr

- name: Update tldr
  become: true
  ansible.builtin.shell: "{{ lookup('env', 'HOME') }}/.local/bin/tldr -u"
  tags:
    - productivitytldr
    - tldr
